kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: o11y

configMapGenerator:
  - name: grafana-dashboard-o11y
    files:
      - dashboards/o11y-dashboard.json

resources:
  - dashboard.yaml
