apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prometheus.pod_alerts.yaml
- prometheus.quota_alerts.yaml
- prometheus.pv_alerts.yaml
- prometheus.controller_alerts.yaml
- prometheus.argocd_alerts.yaml
