apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    openshift.io/prometheus-rule-evaluation-scope: leaf-prometheus
  name: o11y-alerting-rules
  namespace: o11y
spec:
  groups:
  - name: pod_alerts
    rules:
    - alert: UnschedulablePods
      expr: last_over_time(kube_pod_status_unschedulable{namespace!~"(.*-tenant|openshift-.*|kube-.*|default)"}[5m]) == 1
      for: 30m
      labels:
        severity: warning
      annotations:
        summary: "Pod {{ $labels.pod }} cannot be scheduled."
        description: "Pod {{ $labels.pod }} for namespace {{ $labels.namespace }} is unscheduled for more than 30 minutes."
    - alert: CrashLoopBackOff
      expr: max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff", namespace!~"(.*-tenant|openshift-.*|kube-.*|default)"}[5m]) >= 1
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "Pod {{ $labels.pod }} is crash looping"
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is in waiting state (reason: 'CrashLoopBackOff') for more than 15 minutes."
    - alert: PodsNotReady
      expr: |
            kube_pod_status_phase{phase=~"Pending|Unknown|Failed", namespace!~"(.*-tenant|openshift-.*|kube-.*|default)"} == 1
            unless ignoring (phase) (kube_pod_status_unschedulable == 1)
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "Pod {{ $labels.pod }} is not ready"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not ready for more than 15 minutes."
